// The production worker is generated by scripts/build.mjs so every required
// static asset is served directly without depending on an external asset binding.
export default{async fetch(){return new Response('Run npm run build to generate the production worker.',{status:503})}};
